version: '3'

services:
    app:
        container_name: app
        build:
            context: .
            dockerfile: Dockerfile.app
        networks:
            - backend
        volumes:
        - lavagna_app:/app/
        - lavagna_depen:/root/.m2/
        depends_on:
          - mysql
    mysql:
        container_name: mysql
        build:
            context: .
            dockerfile: Dockerfile.db
        networks:
            - backend
        volumes:
            - lavagna_sql:/var/lib/mysql
            #- db:/docker-entrypoint-initdb.d
            #- in:/root/app/in
    proxy:
        container_name: proxy
        build:
            context: .
            dockerfile: Dockerfile.proxy
        ports:
            - "80:80"
        depends_on:
            - app
        networks:
            - backend
networks:
    backend:
volumes:
    lavagna_app:
    lavagna_depen:
    lavagna_sql:
