# FROM node:10.18.0-alpine3.9 as node
# COPY ./project/src/main/webapp /app
# WORKDIR /app

# RUN npm install && npm run build

FROM nginx:stable-alpine
COPY nginx.conf /etc/nginx/nginx.conf
COPY ./project/src/main/webapp/css /static/css
COPY ./project/src/main/webapp/favicon /static/favicon
COPY ./project/src/main/webapp/fonts /static/fonts
COPY ./project/src/main/webapp/js /static/js
COPY ./project/src/main/webapp/svg /static/svg
COPY ./project/src/main/webapp/WEB-INF/views /static


